/* Braat
 * Copyright (C) 2026 Jocelyn Stericker <jocelyn@nettek.ca>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Trigger download of a wav containing the audio buffer.
 *
 * Must be done in response to a click or other event.
 */
export function exportWav(buf: AudioBuffer) {
  // Generated by sonnet.
  const pcm = buf.getChannelData(0)
  const wavBuf = new ArrayBuffer(44 + pcm.length * 2)
  const bytes = new Uint8Array(wavBuf)
  const dv = new DataView(wavBuf)
  bytes.set([82, 73, 70, 70]) // "RIFF"
  dv.setUint32(4, 36 + pcm.length * 2, true)
  bytes.set([87, 65, 86, 69], 8) // "WAVE"
  bytes.set([102, 109, 116, 32], 12) // "fmt "
  dv.setUint32(16, 16, true)
  dv.setUint16(20, 1, true) // PCM
  dv.setUint16(22, 1, true) // mono
  dv.setUint32(24, buf.sampleRate, true)
  dv.setUint32(28, buf.sampleRate * 2, true)
  dv.setUint16(32, 2, true)
  dv.setUint16(34, 16, true)
  bytes.set([100, 97, 116, 97], 36) // "data"
  dv.setUint32(40, pcm.length * 2, true)
  for (let i = 0; i < pcm.length; i++) {
    const s = Math.max(-1, Math.min(1, pcm[i]!))
    dv.setInt16(44 + i * 2, s < 0 ? s * 32768 : s * 32767, true)
  }

  const ts = new Date()
    .toISOString()
    .replace(/[:.]/g, '-')
    .replace('T', '_')
    .slice(0, 19)
  const url = URL.createObjectURL(new Blob([wavBuf], { type: 'audio/wav' }))
  const a = document.createElement('a')
  a.href = url
  a.download = `braat-${ts}.wav`
  a.click()
  URL.revokeObjectURL(url)
}
