// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2015-present Jocelyn Stericker <jocelyn@nettek.ca>

import type { Clef } from "#/musicxml-interfaces";

export const standardClefs: Clef[] = [
  {
    // Treble
    line: 2,
    sign: "G",
    additional: false,
    afterBarline: false,
    clefOctaveChange: null,
    color: "#000000",
    defaultX: -16,
    defaultY: 16,
    fontFamily: "",
    fontSize: "small",
    fontStyle: 0,
    fontWeight: 0,
    number: 1,
    printObject: true,
    relativeX: 0,
    relativeY: 0,
    size: 1,
  },
  {
    // bass
    line: 4,
    sign: "F",
    additional: false,
    afterBarline: false,
    clefOctaveChange: null,
    color: "#000000",
    defaultX: -16,
    defaultY: 4,
    fontFamily: "",
    fontSize: "small",
    fontStyle: 0,
    fontWeight: 0,
    number: 1,
    printObject: true,
    relativeX: 0,
    relativeY: 0,
    size: 1,
  },
  {
    // tenor
    line: 3,
    sign: "C",
    additional: false,
    afterBarline: false,
    clefOctaveChange: null,
    color: "#000000",
    defaultX: -16,
    defaultY: 0,
    fontFamily: "",
    fontSize: "small",
    fontStyle: 0,
    fontWeight: 0,
    number: 1,
    printObject: true,
    relativeX: 0,
    relativeY: 0,
    size: 1,
  },
  {
    // alto
    line: 4,
    sign: "C",
    additional: false,
    afterBarline: false,
    clefOctaveChange: null,
    color: "#000000",
    defaultX: -16,
    defaultY: 8,
    fontFamily: "",
    fontSize: "small",
    fontStyle: 0,
    fontWeight: 0,
    number: 1,
    printObject: true,
    relativeX: 0,
    relativeY: 0,
    size: 1,
  },
  {
    line: 3,
    sign: "PERCUSSION",
    additional: false,
    afterBarline: false,
    clefOctaveChange: null,
    color: "#000000",
    defaultX: -16,
    defaultY: 8,
    fontFamily: "",
    fontSize: "small",
    fontStyle: 0,
    fontWeight: 0,
    number: 1,
    printObject: true,
    relativeX: 0,
    relativeY: 0,
    size: 1,
  },
  {
    line: 5,
    sign: "TAB",
    additional: false,
    afterBarline: false,
    clefOctaveChange: null,
    color: "#000000",
    defaultX: -16,
    defaultY: 8,
    fontFamily: "",
    fontSize: "small",
    fontStyle: 0,
    fontWeight: 0,
    number: 1,
    printObject: true,
    relativeX: 0,
    relativeY: 0,
    size: 1,
  },
];
