/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as Musicxml2lyRouteImport } from './routes/musicxml2ly'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as PlaygroundTestsRouteImport } from './routes/playground/tests'
import { Route as PlaygroundSandboxRouteImport } from './routes/playground/sandbox'
import { Route as PlaygroundTestsIdRouteImport } from './routes/playground/tests.$id'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const Musicxml2lyRoute = Musicxml2lyRouteImport.update({
  id: '/musicxml2ly',
  path: '/musicxml2ly',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundTestsRoute = PlaygroundTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundSandboxRoute = PlaygroundSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundTestsIdRoute = PlaygroundTestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlaygroundTestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/musicxml2ly': typeof Musicxml2lyRoute
  '/playground': typeof PlaygroundRouteWithChildren
  '/status': typeof StatusRoute
  '/playground/sandbox': typeof PlaygroundSandboxRoute
  '/playground/tests': typeof PlaygroundTestsRouteWithChildren
  '/playground/': typeof PlaygroundIndexRoute
  '/playground/tests/$id': typeof PlaygroundTestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/musicxml2ly': typeof Musicxml2lyRoute
  '/status': typeof StatusRoute
  '/playground/sandbox': typeof PlaygroundSandboxRoute
  '/playground/tests': typeof PlaygroundTestsRouteWithChildren
  '/playground': typeof PlaygroundIndexRoute
  '/playground/tests/$id': typeof PlaygroundTestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/musicxml2ly': typeof Musicxml2lyRoute
  '/playground': typeof PlaygroundRouteWithChildren
  '/status': typeof StatusRoute
  '/playground/sandbox': typeof PlaygroundSandboxRoute
  '/playground/tests': typeof PlaygroundTestsRouteWithChildren
  '/playground/': typeof PlaygroundIndexRoute
  '/playground/tests/$id': typeof PlaygroundTestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/musicxml2ly'
    | '/playground'
    | '/status'
    | '/playground/sandbox'
    | '/playground/tests'
    | '/playground/'
    | '/playground/tests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/musicxml2ly'
    | '/status'
    | '/playground/sandbox'
    | '/playground/tests'
    | '/playground'
    | '/playground/tests/$id'
  id:
    | '__root__'
    | '/'
    | '/musicxml2ly'
    | '/playground'
    | '/status'
    | '/playground/sandbox'
    | '/playground/tests'
    | '/playground/'
    | '/playground/tests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Musicxml2lyRoute: typeof Musicxml2lyRoute
  PlaygroundRoute: typeof PlaygroundRouteWithChildren
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicxml2ly': {
      id: '/musicxml2ly'
      path: '/musicxml2ly'
      fullPath: '/musicxml2ly'
      preLoaderRoute: typeof Musicxml2lyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/tests': {
      id: '/playground/tests'
      path: '/tests'
      fullPath: '/playground/tests'
      preLoaderRoute: typeof PlaygroundTestsRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/sandbox': {
      id: '/playground/sandbox'
      path: '/sandbox'
      fullPath: '/playground/sandbox'
      preLoaderRoute: typeof PlaygroundSandboxRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/tests/$id': {
      id: '/playground/tests/$id'
      path: '/$id'
      fullPath: '/playground/tests/$id'
      preLoaderRoute: typeof PlaygroundTestsIdRouteImport
      parentRoute: typeof PlaygroundTestsRoute
    }
  }
}

interface PlaygroundTestsRouteChildren {
  PlaygroundTestsIdRoute: typeof PlaygroundTestsIdRoute
}

const PlaygroundTestsRouteChildren: PlaygroundTestsRouteChildren = {
  PlaygroundTestsIdRoute: PlaygroundTestsIdRoute,
}

const PlaygroundTestsRouteWithChildren = PlaygroundTestsRoute._addFileChildren(
  PlaygroundTestsRouteChildren,
)

interface PlaygroundRouteChildren {
  PlaygroundSandboxRoute: typeof PlaygroundSandboxRoute
  PlaygroundTestsRoute: typeof PlaygroundTestsRouteWithChildren
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
}

const PlaygroundRouteChildren: PlaygroundRouteChildren = {
  PlaygroundSandboxRoute: PlaygroundSandboxRoute,
  PlaygroundTestsRoute: PlaygroundTestsRouteWithChildren,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
}

const PlaygroundRouteWithChildren = PlaygroundRoute._addFileChildren(
  PlaygroundRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Musicxml2lyRoute: Musicxml2lyRoute,
  PlaygroundRoute: PlaygroundRouteWithChildren,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
