/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IpaRouteImport } from './routes/ipa'
import { Route as IndexRouteImport } from './routes/index'

const IpaRoute = IpaRouteImport.update({
  id: '/ipa',
  path: '/ipa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ipa': typeof IpaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ipa': typeof IpaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ipa': typeof IpaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ipa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ipa'
  id: '__root__' | '/' | '/ipa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IpaRoute: typeof IpaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ipa': {
      id: '/ipa'
      path: '/ipa'
      fullPath: '/ipa'
      preLoaderRoute: typeof IpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IpaRoute: IpaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
